# Schema for the configuration files of the tawk_to module.
tawk_to.settings:
  type: config_object
  mapping:
    tawk_to_widget_page_id:
      type: string
      label: 'tawk_to_widget_page_id'
    tawk_to_widget_widget_id:
      type: string
      label: 'tawk_to_widget_widget_id'
